global:
  scrape_interval:     15s
  evaluation_interval: 15s


# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'ace-server'
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['ace-server:9200']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
