{
 "title": "ACE .NET runtime metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(dotnet_build_info, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(dotnet_build_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,2m" }
  ]
 },
 "panels": [
  { "title": "ACE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "description": "**ACEmulator Status** \n\nStatus is marked Online when server is transmitting metric data",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_Process_TotalRunTime{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Server Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_Info{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{server_version}}"
    }
   ]
  },
  {
   "title": "Database Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_Info{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{database_version_base}} | {{database_version_patch}}"
    }
   ]
  },
  {
   "title": "Accounts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_DatabaseManager_AccountCount{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Characters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_PlayerManager_TotalCount{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Players",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_NetworkManager_AuthenticatedSessionCount{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Connected"
    },
    {
     "expr": "ace_PlayerManager_OnlineCount{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "In World"
    },
    {
     "expr": "ace_NetworkManager_AuthenticatedSessionCount{instance=\"$instance\",job=\"$job\"}-ace_PlayerManager_OnlineCount{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Not In World"
    }
   ]
  },
  {
   "title": "Landblocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "ace_LandblockManager_ActiveLandblocks{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Active Landblocks"
    },
    {
     "expr": "ace_LandblockManager_DormantLandblocks{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Dormant Landblocks"
    },
    {
     "expr": "ace_LandblockManager_ActiveDungeons{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Active Dungeons"
    },
    {
     "expr": "ace_LandblockManager_DormantDungeons{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Dormant Dungeons"
    },
    {
     "expr": "ace_LandblockManager_LandblockGroups{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Landblock Groups"
    }
   ]
  },
  {
   "title": "Landblock Objects and ServerObjectManager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "ace_LandblockManager_Objects_Players{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Players"
    },
    {
     "expr": "ace_LandblockManager_Objects_Creatures{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Creatures"
    },
    {
     "expr": "ace_LandblockManager_Objects_Missiles{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Missiles"
    },
    {
     "expr": "ace_LandblockManager_Objects_Other{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Other"
    },
    {
     "expr": "ace_LandblockManager_Objects_Total{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "ace_ServerObjectManager_ServerObjects{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Server Objects"
    }
   ]
  },
  {
   "title": "Core Ticks 5m avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ace_ServerPerformanceMonitor_5m_PlayerManager_Tick_Average{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "PlayerManager"
    },
    {
     "expr": "ace_ServerPerformanceMonitor_5m_NetworkManager_InboundClientMessageQueueRun_Average{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "NetworkManager_InboundClientMessageQueueRun"
    },
    {
     "expr": "ace_ServerPerformanceMonitor_5m_actionQueue_RunActions_Average{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "actionQueue_RunActions"
    },
    {
     "expr": "ace_ServerPerformanceMonitor_5m_DelayManager_RunActions_Average{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "DelayManager_RunActions"
    },
    {
     "expr": "ace_ServerPerformanceMonitor_5m_UpdateGameWorld_Average{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "UpdateGameWorld"
    },
    {
     "expr": "ace_ServerPerformanceMonitor_5m_NetworkManager_DoSessionWork_Average{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "NetworkManager_DoSessionWork"
    },
    {
     "expr": "dotnet_build_info{instance=\"$instance\",job=\"$job\"}+-0.984",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "DatabaseManager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "ace_DatabaseManager_Shard_CachedPlayerBiotas{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Cached Player Biotas"
    },
    {
     "expr": "ace_DatabaseManager_Shard_CachedNonPlayerBiotas{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Cached NonPlayer Biotas"
    }
   ]
  },
  {
   "title": "NetworkManager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "ace_NetworkManager_SessionCount{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Total Sessions"
    },
    {
     "expr": "ace_NetworkManager_AuthenticatedSessionCount{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Authenticated Sessions"
    },
    {
     "expr": "ace_NetworkManager_UniqueSessionEndpointCount{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Unique Sessions"
    }
   ]
  },
  {
   "title": "UpdateGameWorld Tick",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ace_ServerPerformanceMonitor_5m_UpdateGameWorld_Entire_Average{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "5m avg"
    },
    {
     "expr": "ace_ServerPerformanceMonitor_5m_UpdateGameWorld_Entire_Longest{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "5m longest"
    },
    {
     "expr": "ace_ServerPerformanceMonitor_1h_UpdateGameWorld_Entire_Average{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "1h avg"
    },
    {
     "expr": "dotnet_build_info{instance=\"$instance\",job=\"$job\"}+-0.984",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "DatabaseManager Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "ace_DatabaseManager_Shard_QueueCount{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Queue"
    },
    {
     "expr": "ace_DatabaseManager_Shard_QueueWaitTime{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Wait Time"
    }
   ]
  },
  {
   "title": "PlayerManager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "ace_PlayerManager_OnlineCount{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "Calls from WorldManager.UpdateGameWorld 5m avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ace_ServerPerformanceMonitor_5m_LandblockManager_TickPhysics_Average{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "TickPhysics"
    },
    {
     "expr": "ace_ServerPerformanceMonitor_5m_LandblockManager_TickMultiThreadedWork_Average{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "TickMultiThreadedWork"
    },
    {
     "expr": "ace_ServerPerformanceMonitor_5m_LandblockManager_TickSingleThreadedWork_Average{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "TickSingleThreadedWork"
    },
    {
     "expr": "dotnet_build_info{instance=\"$instance\",job=\"$job\"}+-0.984",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "GuidManager Players",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "hex0x" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_GuidManager_PlayerGuidAllocator_Min{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "ace_GuidManager_PlayerGuidAllocator_Max{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "ace_GuidManager_PlayerGuidAllocator_Current{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "GuidManager Dynamic",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "hex0x" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_GuidManager_DynamicGuidAllocator_Min{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "ace_GuidManager_DynamicGuidAllocator_Max{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "ace_GuidManager_DynamicGuidAllocator_Current{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 1, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_GuidManager_DynamicGuidAllocator_SequenceGapPairsTotal{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Pairs"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 1, "x": 7, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_GuidManager_DynamicGuidAllocator_RecycledGuidsTotal{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Recycled"
    }
   ]
  },
  {
   "title": "GuidManager Dynamic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "ace_GuidManager_DynamicGuidAllocator_SequenceGapPairsTotal{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Sequence Gap Pairs"
    },
    {
     "expr": "ace_GuidManager_DynamicGuidAllocator_RecycledGuidsTotal{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Recycled Guids Available"
    }
   ]
  },
  {
   "title": "AllegianceManager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "ace_AllegianceManager_AllegiancesLoadedInMemory{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Allegiances"
    },
    {
     "expr": "ace_AllegianceManager_PlayersMappedInMemory{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Players"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "hex0x" } },
   "targets": [
    {
     "expr": "ace_GuidManager_PlayerGuidAllocator_Current{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Players"
    },
    {
     "expr": "ace_GuidManager_DynamicGuidAllocator_Current{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Dynamic"
    }
   ]
  },
  {
   "title": "HouseManager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "ace_HouseManager_TotalOwnedHousing{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Total Owned Housing"
    },
    {
     "expr": "ace_HouseManager_TotalOwnedApartments{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Apartments"
    },
    {
     "expr": "ace_HouseManager_TotalOwnedCottages{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Cottages"
    },
    {
     "expr": "ace_HouseManager_TotalOwnedVillas{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Villas"
    },
    {
     "expr": "ace_HouseManager_TotalOwnedMansions{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Mansions"
    }
   ]
  },
  {
   "title": "Housing Totals",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "3000-ace_HouseManager_TotalOwnedApartments{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Apartments Available"
    },
    {
     "expr": "ace_HouseManager_TotalOwnedApartments{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Apartments Owned"
    },
    {
     "expr": "2600-ace_HouseManager_TotalOwnedCottages{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Cottages Available"
    },
    {
     "expr": "ace_HouseManager_TotalOwnedCottages{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Cottages Owned"
    },
    {
     "expr": "570-ace_HouseManager_TotalOwnedVillas{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Villas Available"
    },
    {
     "expr": "ace_HouseManager_TotalOwnedVillas{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Villas Owned"
    },
    {
     "expr": "80-ace_HouseManager_TotalOwnedMansions{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Mansions Available"
    },
    {
     "expr": "ace_HouseManager_TotalOwnedMansions{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Mansions Owned"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_HouseManager_TotalOwnedApartments{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Apartments"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_HouseManager_TotalOwnedCottages{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Cottages"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_HouseManager_TotalOwnedVillas{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Villas"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_HouseManager_TotalOwnedMansions{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Mansions"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ace_HouseManager_TotalOwnedHousing{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Mansions"
    }
   ]
  },
  { "title": "Current Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "% CPU consumption",
   "type": "stat",
   "description": "The percentage of available CPU resources consumed.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}[$__interval]) / process_cpu_count{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "% Memory consumption",
   "type": "stat",
   "description": "The percentage of available memory resources consumed.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_working_set_bytes{instance=\"$instance\",job=\"$job\"} / dotnet_gc_memory_total_available_bytes{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "% Paused time",
   "type": "stat",
   "description": "The percentage of time that the application was paused to allow the garbage collector to run.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_gc_pause_ratio{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "% GC CPU consumption",
   "type": "stat",
   "description": "The percentage of total process CPU utilization that was dedicated to performing garbage collections.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_gc_cpu_ratio{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Thread pool queue length",
   "type": "stat",
   "description": "The average length of the thread pool's work queue. Values greater than 0 indicate a problem.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_threadpool_queue_length_sum{instance=\"$instance\",job=\"$job\"}[$__rate_interval]))  / \nsum(rate(dotnet_threadpool_queue_length_count{instance=\"$instance\",job=\"$job\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "% JIT CPU consumption",
   "type": "stat",
   "description": "The percentage of CPU utilization that was dedicated to compiling methods by the Just In Time (JIT) compiler.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_jit_cpu_ratio{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Exceptions/ sec",
   "type": "stat",
   "description": "The rate of exceptions being thrown per second",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_exceptions_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Memory / Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Memory use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_working_set_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "# bytes (in physical memory)"
    },
    {
     "expr": "dotnet_gc_memory_total_available_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Total bytes available (memory limit)"
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dotnet_gc_heap_size_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "gen {{gc_generation}}"
    }
   ]
  },
  {
   "title": "GC CPU + pause ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dotnet_gc_cpu_ratio{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "GC CPU %"
    },
    {
     "expr": "dotnet_gc_pause_ratio{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "GC Pause %"
    }
   ]
  },
  {
   "title": "Number of GC collections/ sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_collection_count_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])) by (gc_generation, gc_reason)",
     "legendFormat": "gen {{gc_generation}}: {{gc_reason}}"
    }
   ]
  },
  {
   "title": "Bytes allocated (by heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_allocated_bytes_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])) by (gc_heap)",
     "legendFormat": "Alloc bytes {{gc_heap}}"
    }
   ]
  },
  {
   "title": "Average GC duration (by generation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_seconds_sum{instance=\"$instance\",job=\"$job\"}[$__rate_interval])) by (gc_generation) / sum(increase(dotnet_gc_collection_seconds_count{instance=\"$instance\",job=\"$job\"}[$__rate_interval])) by (gc_generation) ",
     "legendFormat": "{{gc_generation}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_seconds_bucket{instance=\"$instance\",job=\"$job\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Thread pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread pool queue length",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sum by (le) (increase(dotnet_threadpool_queue_length_bucket{instance=\"$instance\",job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Num thread pool threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "targets": [
      {
       "expr": "dotnet_threadpool_num_threads{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Num thread timers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "targets": [
      {
       "expr": "dotnet_threadpool_timer_count{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Thread pool adjustment reasons",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "sum(increase(dotnet_threadpool_adjustments_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])) by (adjustment_reason )",
       "legendFormat": "{{adjustment_reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JIT compliation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Methods compiled/ sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "rate(dotnet_jit_method_total{dynamic=\"true\", instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Dynamic methods"
      },
      {
       "expr": "rate(dotnet_jit_method_total{dynamic=\"false\", instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Methods"
      }
     ]
    },
    {
     "title": "JIT CPU usage ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "dotnet_jit_cpu_ratio{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "% CPU utilization"
      }
     ]
    }
   ]
  },
  {
   "title": "Contention",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locks contended/ sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "rate(dotnet_contention_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "# Locks contended"
      }
     ]
    },
    {
     "title": "Time waiting for locks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "increase(dotnet_contention_seconds_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Waiting time"
      }
     ]
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exceptions/ sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "rate(dotnet_exceptions_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  { "title": "Sockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Bytes sent vs received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "rate(dotnet_sockets_bytes_received_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Received/ sec"
    },
    {
     "expr": "rate(dotnet_sockets_bytes_sent_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Sent/ sec"
    }
   ]
  },
  {
   "title": "Connections established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "increase(dotnet_sockets_connections_established_incoming_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Incoming "
    },
    {
     "expr": "increase(dotnet_sockets_connections_established_outgoing_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Outgoing"
    }
   ]
  }
 ]
}